### PR TITLE
Uninstall at stop

### PR DESCRIPTION
**Pull request by tbaumann**
When charm is removed the agent keeps running. This can have unintended consequences.

Since this is a subordinate, it seems prudent to clean up afterwards so that the main unit can keep running unimpeded.

### CODE REVIEW

**Comment by chuckbutler** [comment]
this looks like you based it on the kafka branch, but the base-layer kafka support is not current merged (it conflicted as soon as I merged the stop branch). 

Can you tease these apart and resubmit the PR?

**Review by lazypower — CHANGES_REQUESTED** [review]
this looks like you based it on the kafka branch, but the base-layer kafka support is not currently merged (it conflicted as soon as I merged the stop branch).

Can you tease these apart and resubmit the PR?

**Comment by tbaumann** [comment]
Sorry, that wasn't intentional. My mistake. Will resubmit

**Comment by tbaumann** [comment]
I rebased the branch

**Comment by lazypower** [comment]
👍  LGTM thanks for the cleanup

**Pull request merged**
